[project]
name = "whisper-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.6",
    "loguru>=0.7.3",
    "mlx-whisper>=0.4.1",
    "numpy>=2.0.2",
    # "fastapi>=0.115.6",
    # "loguru>=0.7.3",
    # "numpy>=2.2.1",
    "openai>=1.59.7",
    "pip>=24.3.1",
    "pydantic>=2.10.5",
    "pyyaml>=6.0.2",
    "sounddevice>=0.5.1",
    "typer>=0.15.1",
    "uvicorn>=0.34.0",
    "webrtcvad>=2.0.10",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "isort>=5.13.2",
    "pytest>=8.3.4",
]

[tool.isort]
profile = "black"